// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * this is the struct type that hosts the methods for
 * app services.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * mostly useful at startup of app when events cannot
 * be used
 * @returns {$CancellablePromise<string>}
 */
export function Html() {
    return $Call.ByID(352644965);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenExternal(url) {
    return $Call.ByID(2019505343, url);
}
