// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * the following struct is used for sending theme changes to frontend.
 */
export class cssTheme {
    /**
     * Creates a new cssTheme instance.
     * @param {Partial<cssTheme>} [$$source = {}] - The source object to create the cssTheme.
     */
    constructor($$source = {}) {
        if (!("Target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Target"] = "";
        }
        if (!("Color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Color"] = "";
        }
        if (!("Font" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Font"] = "";
        }
        if (!("Size" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Size"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new cssTheme instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {cssTheme}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new cssTheme(/** @type {Partial<cssTheme>} */($$parsedSource));
    }
}

export class metadata {
    /**
     * Creates a new metadata instance.
     * @param {Partial<metadata>} [$$source = {}] - The source object to create the metadata.
     */
    constructor($$source = {}) {
        if (!("Target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Target"] = "";
        }
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("WordCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["WordCount"] = 0;
        }
        if (!("ShortPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ShortPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new metadata instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {metadata}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new metadata(/** @type {Partial<metadata>} */($$parsedSource));
    }
}

/**
 * We use this to send update to frontend.
 * Need to specify Target because Wails3
 * does not (yet?) support sending an event to just
 * one Window.
 */
export class update {
    /**
     * Creates a new update instance.
     * @param {Partial<update>} [$$source = {}] - The source object to create the update.
     */
    constructor($$source = {}) {
        if (!("Target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Target"] = "";
        }
        if (!("Html" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Html"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new update instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {update}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new update(/** @type {Partial<update>} */($$parsedSource));
    }
}
