// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../../mdpreview/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "newmetadata": main$0.metadata;
            "newplaintext": string;
            "themechange": main$0.cssTheme;
            "updatefile": main$0.update;
        }
    }
}
